-- Updated view for distinct vendor_id and vendro_name

create or replace view RETAIL_ANALYTICS.CLEAN.VENDOR_INVOICES_LAST_YEAR(
	TRANSACTION_ID,
	STORE_ID,
	CITY,
	STATE,
	REGION,
	VENDOR_ID,
	VENDOR_NAME,
	VENDOR_CATEGORY,
	DATE_ID,
	DATE,
	SKU_COUNT,
	TOTAL_ITEMS,
	INVOICE_AMOUNT,
	VENDOR_SIZE,
	INVOICE_INITIATED_TS,
	INVOICE_FINISHED_TS
) as
SELECT *
FROM VENDOR_INVOICES_2024
WHERE date >= '2024-10-01'::DATE

UNION ALL

SELECT *
FROM VENDOR_INVOICES_2025
WHERE date < '2025-10-01'::DATE;


/*
Run date: 2025-12-01
*/
